# Generated by Django 4.2.3 on 2023-07-18 18:17

import customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        validators=[customers.models.email_validator],
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        null=True,
                        validators=[customers.models.mobile_validator],
                    ),
                ),
                (
                    "linkPrecidence",
                    models.CharField(
                        choices=[("primary", "primary"), ("secondary", "secondary")],
                        max_length=40,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                (
                    "linkedId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.contacts",
                    ),
                ),
            ],
        ),
    ]
